#设置端口号
server:
  port: 80


comment:
  avatar: /images/moren.jpg

#别名
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nandu.pojo
# 分页
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true

#日志
logging:
  level:
    root: info
#   file: log/blog.log

spring:
#  mail:
#    host: smtp.qq.com
#    username: 1732190917@qq.com
#    password: ogqleaoxrnbkeaha
#    # qq需要配置ssl,开启加密
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
  # 关闭thymeleaf的缓存(热部署)
  thymeleaf:
    cache: false

#  mvc:
#    favicon:
#      enabled: false;
  #  mail:
#    username: 1732190917@qq.com
#    password: ogqleaoxrnbkeaha
#    host: smtp.qq.com
#    # qq需要配置ssl,开启加密
#    properties: mail.smtp.ssl.enable=true


#  jpa.hibernate.ddl-auto是hibernate的配置属性，其主要作用是：自动创建、更新、验证数据库表结构。该参数的几种配置如下：
#  ·create：每次加载hibernate时都会删除上一次的生成的表，然后根据你的model类再重新来生成新表，哪怕两次没有任何改变也要这样执行，这就是导致数据库表数据丢失的一个重要原因。
#  ·create-drop：每次加载hibernate时根据model类生成表，但是sessionFactory一关闭,表就自动删除。
#  ·update：最常用的属性，第一次加载hibernate时根据model类会自动建立起表的结构（前提是先建立好数据库），以后加载hibernate时根据model类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行。要注意的是当部署到服务器后，表结构是不会被马上建立起来的，是要等应用第一次运行起来后才会。
#  ·validate：每次加载hibernate时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值。
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: #账号
    password: #密码
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      aop-patterns: 'com.nandu.service # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔'
      filters: stat
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 1
      pool-prepared-statements: false
      # druid数据库监控配置
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: true
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        principal-cookie-name: admin
        principal-session-name: admin
        profile-enable: true
        session-stat-enable: false
        session-stat-max-count: 1000
        url-pattern: /*
